CI update again :)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -17,7 +17,7 @@ jobs:
         run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;
 
       - name: Typecheck
-        run: npm typecheck
+        run: npm typecheck || { echo "Typecheck failed"; exit 1; }
 
       - name: Lint
-        run: npm lint
+        run: npm lint || { echo "Linting failed"; exit 1; }
